// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(PharmacyContext))]
    [Migration("20260106195015_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Active_Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("active_ingredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Paracetamol"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ibuprofen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Amoxicillin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cetirizine"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Loratadine"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Azithromycin"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Metformin"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Omeprazole"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Aspirin"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Dextromethorphan"
                        });
                });

            modelBuilder.Entity("Data.Models.Batch", b =>
                {
                    b.Property<int>("Batch_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Batch_Id"));

                    b.Property<int>("Alert_Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Arrival_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Batch_Num")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expiri_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Initial_Quantity")
                        .HasColumnType("int");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("Purchase_OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("Purchase_Order_ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("RefrigeratorId")
                        .HasColumnType("int");

                    b.Property<int>("Stock_Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Unit_Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Batch_Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("Purchase_OrderId");

                    b.HasIndex("Purchase_Order_ItemId");

                    b.HasIndex("RefrigeratorId");

                    b.ToTable("batches", (string)null);

                    b.HasData(
                        new
                        {
                            Batch_Id = 1,
                            Alert_Quantity = 0,
                            Arrival_Date = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Batch_Num = "BTH-2024-001",
                            Expiri_Date = new DateTime(2026, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initial_Quantity = 100,
                            MedicineId = 1,
                            Purchase_OrderId = 1,
                            Stock_Quantity = 100,
                            Unit_Price = 1275.00m
                        },
                        new
                        {
                            Batch_Id = 2,
                            Alert_Quantity = 0,
                            Arrival_Date = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Batch_Num = "BTH-2024-002",
                            Expiri_Date = new DateTime(2026, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initial_Quantity = 150,
                            MedicineId = 2,
                            Purchase_OrderId = 1,
                            Stock_Quantity = 150,
                            Unit_Price = 2700.00m
                        },
                        new
                        {
                            Batch_Id = 3,
                            Alert_Quantity = 0,
                            Arrival_Date = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Batch_Num = "BTH-2024-003",
                            Expiri_Date = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initial_Quantity = 80,
                            MedicineId = 3,
                            Purchase_OrderId = 2,
                            Stock_Quantity = 80,
                            Unit_Price = 1200.00m
                        },
                        new
                        {
                            Batch_Id = 4,
                            Alert_Quantity = 0,
                            Arrival_Date = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Batch_Num = "BTH-2024-004",
                            Expiri_Date = new DateTime(2027, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initial_Quantity = 200,
                            MedicineId = 4,
                            Purchase_OrderId = 2,
                            Stock_Quantity = 200,
                            Unit_Price = 3000.00m
                        },
                        new
                        {
                            Batch_Id = 5,
                            Alert_Quantity = 0,
                            Arrival_Date = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Batch_Num = "BTH-2024-005",
                            Expiri_Date = new DateTime(2027, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initial_Quantity = 120,
                            MedicineId = 5,
                            Purchase_OrderId = 4,
                            Stock_Quantity = 120,
                            Unit_Price = 1800.00m
                        },
                        new
                        {
                            Batch_Id = 6,
                            Alert_Quantity = 0,
                            Arrival_Date = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Batch_Num = "BTH-2024-006",
                            Expiri_Date = new DateTime(2026, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initial_Quantity = 90,
                            MedicineId = 6,
                            Purchase_OrderId = 6,
                            RefrigeratorId = 1,
                            Stock_Quantity = 90,
                            Unit_Price = 4950.00m
                        },
                        new
                        {
                            Batch_Id = 7,
                            Alert_Quantity = 0,
                            Arrival_Date = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Batch_Num = "BTH-2024-007",
                            Expiri_Date = new DateTime(2027, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initial_Quantity = 180,
                            MedicineId = 8,
                            Purchase_OrderId = 8,
                            Stock_Quantity = 180,
                            Unit_Price = 5130.00m
                        },
                        new
                        {
                            Batch_Id = 8,
                            Alert_Quantity = 0,
                            Arrival_Date = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Batch_Num = "BTH-2024-008",
                            Expiri_Date = new DateTime(2027, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initial_Quantity = 140,
                            MedicineId = 9,
                            Purchase_OrderId = 1,
                            Stock_Quantity = 140,
                            Unit_Price = 1680.00m
                        },
                        new
                        {
                            Batch_Id = 9,
                            Alert_Quantity = 0,
                            Arrival_Date = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Batch_Num = "BTH-2024-009",
                            Expiri_Date = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initial_Quantity = 75,
                            MedicineId = 10,
                            Purchase_OrderId = 8,
                            RefrigeratorId = 2,
                            Stock_Quantity = 75,
                            Unit_Price = 1125.00m
                        },
                        new
                        {
                            Batch_Id = 10,
                            Alert_Quantity = 0,
                            Arrival_Date = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Batch_Num = "BTH-2024-010",
                            Expiri_Date = new DateTime(2027, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initial_Quantity = 110,
                            MedicineId = 7,
                            Purchase_OrderId = 2,
                            Stock_Quantity = 110,
                            Unit_Price = 2750.00m
                        });
                });

            modelBuilder.Entity("Data.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bayer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pfizer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Novartis"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Johnson & Johnson"
                        },
                        new
                        {
                            Id = 5,
                            Name = "GSK"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sanofi"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Roche"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Merck"
                        },
                        new
                        {
                            Id = 9,
                            Name = "AstraZeneca"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Teva"
                        });
                });

            modelBuilder.Entity("Data.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active_IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Dosage")
                        .HasColumnType("int");

                    b.Property<bool>("Is_Child_form")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Prescription_Required")
                        .HasColumnType("bit");

                    b.Property<string>("Release_Form")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Seasonal_Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Storage_Conditions")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Active_IngredientId");

                    b.HasIndex("BrandId");

                    b.ToTable("medicines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active_IngredientId = 1,
                            BrandId = 1,
                            Dosage = 500,
                            Is_Child_form = false,
                            Name = "Panadol",
                            Prescription_Required = false,
                            Release_Form = "Tablets",
                            Seasonal_Status = "Year-round",
                            Storage_Conditions = "Room temperature"
                        },
                        new
                        {
                            Id = 2,
                            Active_IngredientId = 2,
                            BrandId = 2,
                            Dosage = 400,
                            Is_Child_form = false,
                            Name = "Nurofen",
                            Prescription_Required = false,
                            Release_Form = "Tablets",
                            Seasonal_Status = "Year-round",
                            Storage_Conditions = "Room temperature"
                        },
                        new
                        {
                            Id = 3,
                            Active_IngredientId = 3,
                            BrandId = 3,
                            Dosage = 250,
                            Is_Child_form = false,
                            Name = "Amoxil",
                            Prescription_Required = true,
                            Release_Form = "Capsules",
                            Seasonal_Status = "Year-round",
                            Storage_Conditions = "Room temperature"
                        },
                        new
                        {
                            Id = 4,
                            Active_IngredientId = 4,
                            BrandId = 4,
                            Dosage = 10,
                            Is_Child_form = false,
                            Name = "Zyrtec",
                            Prescription_Required = false,
                            Release_Form = "Tablets",
                            Seasonal_Status = "Spring/Fall",
                            Storage_Conditions = "Room temperature"
                        },
                        new
                        {
                            Id = 5,
                            Active_IngredientId = 5,
                            BrandId = 5,
                            Dosage = 10,
                            Is_Child_form = false,
                            Name = "Claritin",
                            Prescription_Required = false,
                            Release_Form = "Tablets",
                            Seasonal_Status = "Spring/Fall",
                            Storage_Conditions = "Room temperature"
                        },
                        new
                        {
                            Id = 6,
                            Active_IngredientId = 6,
                            BrandId = 6,
                            Dosage = 500,
                            Is_Child_form = false,
                            Name = "Zithromax",
                            Prescription_Required = true,
                            Release_Form = "Tablets",
                            Seasonal_Status = "Year-round",
                            Storage_Conditions = "Room temperature"
                        },
                        new
                        {
                            Id = 7,
                            Active_IngredientId = 7,
                            BrandId = 7,
                            Dosage = 850,
                            Is_Child_form = false,
                            Name = "Glucophage",
                            Prescription_Required = true,
                            Release_Form = "Tablets",
                            Seasonal_Status = "Year-round",
                            Storage_Conditions = "Room temperature"
                        },
                        new
                        {
                            Id = 8,
                            Active_IngredientId = 8,
                            BrandId = 8,
                            Dosage = 20,
                            Is_Child_form = false,
                            Name = "Prilosec",
                            Prescription_Required = false,
                            Release_Form = "Capsules",
                            Seasonal_Status = "Year-round",
                            Storage_Conditions = "Room temperature"
                        },
                        new
                        {
                            Id = 9,
                            Active_IngredientId = 9,
                            BrandId = 1,
                            Dosage = 100,
                            Is_Child_form = false,
                            Name = "Aspirin Bayer",
                            Prescription_Required = false,
                            Release_Form = "Tablets",
                            Seasonal_Status = "Year-round",
                            Storage_Conditions = "Room temperature"
                        },
                        new
                        {
                            Id = 10,
                            Active_IngredientId = 10,
                            BrandId = 9,
                            Dosage = 15,
                            Is_Child_form = true,
                            Name = "Robitussin",
                            Prescription_Required = false,
                            Release_Form = "Syrup",
                            Seasonal_Status = "Winter",
                            Storage_Conditions = "Room temperature"
                        });
                });

            modelBuilder.Entity("Data.Models.Purchase_Order", b =>
                {
                    b.Property<int>("Purchase_Order_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Purchase_Order_Id"));

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Purchase_Order_Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("purchase_orders", (string)null);

                    b.HasData(
                        new
                        {
                            Purchase_Order_Id = 1,
                            Order_Date = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            SupplierId = 1
                        },
                        new
                        {
                            Purchase_Order_Id = 2,
                            Order_Date = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            SupplierId = 2
                        },
                        new
                        {
                            Purchase_Order_Id = 3,
                            Order_Date = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            SupplierId = 3
                        },
                        new
                        {
                            Purchase_Order_Id = 4,
                            Order_Date = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            SupplierId = 4
                        },
                        new
                        {
                            Purchase_Order_Id = 5,
                            Order_Date = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "In Transit",
                            SupplierId = 5
                        },
                        new
                        {
                            Purchase_Order_Id = 6,
                            Order_Date = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            SupplierId = 6
                        },
                        new
                        {
                            Purchase_Order_Id = 7,
                            Order_Date = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            SupplierId = 7
                        },
                        new
                        {
                            Purchase_Order_Id = 8,
                            Order_Date = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            SupplierId = 8
                        },
                        new
                        {
                            Purchase_Order_Id = 9,
                            Order_Date = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "In Transit",
                            SupplierId = 9
                        },
                        new
                        {
                            Purchase_Order_Id = 10,
                            Order_Date = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            SupplierId = 10
                        });
                });

            modelBuilder.Entity("Data.Models.Purchase_Order_Item", b =>
                {
                    b.Property<int>("Purchase_Order_Item_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Purchase_Order_Item_Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("Purchase_orderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Purchase_Order_Item_Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("Purchase_orderId");

                    b.ToTable("purchase_order_items", (string)null);

                    b.HasData(
                        new
                        {
                            Purchase_Order_Item_Id = 1,
                            MedicineId = 1,
                            Purchase_orderId = 1,
                            Quantity = 100
                        },
                        new
                        {
                            Purchase_Order_Item_Id = 2,
                            MedicineId = 2,
                            Purchase_orderId = 1,
                            Quantity = 150
                        },
                        new
                        {
                            Purchase_Order_Item_Id = 3,
                            MedicineId = 3,
                            Purchase_orderId = 2,
                            Quantity = 80
                        },
                        new
                        {
                            Purchase_Order_Item_Id = 4,
                            MedicineId = 4,
                            Purchase_orderId = 2,
                            Quantity = 200
                        },
                        new
                        {
                            Purchase_Order_Item_Id = 5,
                            MedicineId = 5,
                            Purchase_orderId = 3,
                            Quantity = 120
                        },
                        new
                        {
                            Purchase_Order_Item_Id = 6,
                            MedicineId = 6,
                            Purchase_orderId = 4,
                            Quantity = 90
                        },
                        new
                        {
                            Purchase_Order_Item_Id = 7,
                            MedicineId = 7,
                            Purchase_orderId = 5,
                            Quantity = 110
                        },
                        new
                        {
                            Purchase_Order_Item_Id = 8,
                            MedicineId = 8,
                            Purchase_orderId = 6,
                            Quantity = 180
                        },
                        new
                        {
                            Purchase_Order_Item_Id = 9,
                            MedicineId = 9,
                            Purchase_orderId = 7,
                            Quantity = 140
                        },
                        new
                        {
                            Purchase_Order_Item_Id = 10,
                            MedicineId = 10,
                            Purchase_orderId = 8,
                            Quantity = 75
                        });
                });

            modelBuilder.Entity("Data.Models.Recipe", b =>
                {
                    b.Property<int>("Recipe_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Recipe_Id"));

                    b.Property<bool>("Can_use_alternative")
                        .HasColumnType("bit");

                    b.Property<string>("Doctor_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Doctor_Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.HasKey("Recipe_Id");

                    b.HasIndex("MedicineId");

                    b.ToTable("recipes", (string)null);

                    b.HasData(
                        new
                        {
                            Recipe_Id = 1,
                            Can_use_alternative = true,
                            Doctor_Name = "Dr. Ivan Petrov",
                            Doctor_Phone = "+380671234567",
                            MedicineId = 3
                        },
                        new
                        {
                            Recipe_Id = 2,
                            Can_use_alternative = false,
                            Doctor_Name = "Dr. Olena Kovalenko",
                            Doctor_Phone = "+380672345678",
                            MedicineId = 6
                        },
                        new
                        {
                            Recipe_Id = 3,
                            Can_use_alternative = true,
                            Doctor_Name = "Dr. Andriy Shevchenko",
                            Doctor_Phone = "+380673456789",
                            MedicineId = 7
                        },
                        new
                        {
                            Recipe_Id = 4,
                            Can_use_alternative = true,
                            Doctor_Name = "Dr. Maria Bondarenko",
                            Doctor_Phone = "+380674567890",
                            MedicineId = 3
                        },
                        new
                        {
                            Recipe_Id = 5,
                            Can_use_alternative = false,
                            Doctor_Name = "Dr. Ivan Petrov",
                            Doctor_Phone = "+380671234567",
                            MedicineId = 6
                        },
                        new
                        {
                            Recipe_Id = 6,
                            Can_use_alternative = true,
                            Doctor_Name = "Dr. Serhiy Lysenko",
                            Doctor_Phone = "+380675678901",
                            MedicineId = 7
                        },
                        new
                        {
                            Recipe_Id = 7,
                            Can_use_alternative = false,
                            Doctor_Name = "Dr. Olena Kovalenko",
                            Doctor_Phone = "+380672345678",
                            MedicineId = 3
                        },
                        new
                        {
                            Recipe_Id = 8,
                            Can_use_alternative = true,
                            Doctor_Name = "Dr. Natalia Tkachenko",
                            Doctor_Phone = "+380676789012",
                            MedicineId = 6
                        },
                        new
                        {
                            Recipe_Id = 9,
                            Can_use_alternative = true,
                            Doctor_Name = "Dr. Andriy Shevchenko",
                            Doctor_Phone = "+380673456789",
                            MedicineId = 7
                        },
                        new
                        {
                            Recipe_Id = 10,
                            Can_use_alternative = false,
                            Doctor_Name = "Dr. Maria Bondarenko",
                            Doctor_Phone = "+380674567890",
                            MedicineId = 3
                        });
                });

            modelBuilder.Entity("Data.Models.Refrigerator", b =>
                {
                    b.Property<int>("Refrigerator_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Refrigerator_Id"));

                    b.Property<string>("Refrigerator_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Refrigerator_Id");

                    b.ToTable("refrigerators", (string)null);

                    b.HasData(
                        new
                        {
                            Refrigerator_Id = 1,
                            Refrigerator_Name = "Main Storage Fridge A"
                        },
                        new
                        {
                            Refrigerator_Id = 2,
                            Refrigerator_Name = "Main Storage Fridge B"
                        },
                        new
                        {
                            Refrigerator_Id = 3,
                            Refrigerator_Name = "Vaccine Storage Unit"
                        },
                        new
                        {
                            Refrigerator_Id = 4,
                            Refrigerator_Name = "Insulin Storage Fridge"
                        },
                        new
                        {
                            Refrigerator_Id = 5,
                            Refrigerator_Name = "Backup Cooling Unit"
                        });
                });

            modelBuilder.Entity("Data.Models.Refrigerator_Log", b =>
                {
                    b.Property<int>("Log_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Log_Id"));

                    b.Property<double>("Current_Temp")
                        .HasColumnType("float");

                    b.Property<DateTime>("Log_Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Max_Temp")
                        .HasColumnType("float");

                    b.Property<double>("Min_Temp")
                        .HasColumnType("float");

                    b.Property<int>("RefrigeratorId")
                        .HasColumnType("int");

                    b.HasKey("Log_Id");

                    b.HasIndex("RefrigeratorId");

                    b.ToTable("refrigerator_logs", (string)null);

                    b.HasData(
                        new
                        {
                            Log_Id = 1,
                            Current_Temp = 5.2000000000000002,
                            Log_Date = new DateTime(2024, 11, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Max_Temp = 8.0,
                            Min_Temp = 2.0,
                            RefrigeratorId = 1
                        },
                        new
                        {
                            Log_Id = 2,
                            Current_Temp = 4.7999999999999998,
                            Log_Date = new DateTime(2024, 11, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Max_Temp = 8.0,
                            Min_Temp = 2.0,
                            RefrigeratorId = 1
                        },
                        new
                        {
                            Log_Id = 3,
                            Current_Temp = 6.0999999999999996,
                            Log_Date = new DateTime(2024, 11, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Max_Temp = 8.0,
                            Min_Temp = 2.0,
                            RefrigeratorId = 2
                        },
                        new
                        {
                            Log_Id = 4,
                            Current_Temp = 5.5,
                            Log_Date = new DateTime(2024, 11, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Max_Temp = 8.0,
                            Min_Temp = 2.0,
                            RefrigeratorId = 2
                        },
                        new
                        {
                            Log_Id = 5,
                            Current_Temp = 3.8999999999999999,
                            Log_Date = new DateTime(2024, 11, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Max_Temp = 8.0,
                            Min_Temp = 2.0,
                            RefrigeratorId = 3
                        },
                        new
                        {
                            Log_Id = 6,
                            Current_Temp = 4.2000000000000002,
                            Log_Date = new DateTime(2024, 11, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Max_Temp = 8.0,
                            Min_Temp = 2.0,
                            RefrigeratorId = 3
                        },
                        new
                        {
                            Log_Id = 7,
                            Current_Temp = 5.7999999999999998,
                            Log_Date = new DateTime(2024, 11, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Max_Temp = 8.0,
                            Min_Temp = 2.0,
                            RefrigeratorId = 4
                        },
                        new
                        {
                            Log_Id = 8,
                            Current_Temp = 6.2999999999999998,
                            Log_Date = new DateTime(2024, 11, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Max_Temp = 8.0,
                            Min_Temp = 2.0,
                            RefrigeratorId = 4
                        },
                        new
                        {
                            Log_Id = 9,
                            Current_Temp = 4.5,
                            Log_Date = new DateTime(2024, 11, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Max_Temp = 8.0,
                            Min_Temp = 2.0,
                            RefrigeratorId = 5
                        },
                        new
                        {
                            Log_Id = 10,
                            Current_Temp = 5.0,
                            Log_Date = new DateTime(2024, 11, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Max_Temp = 8.0,
                            Min_Temp = 2.0,
                            RefrigeratorId = 5
                        });
                });

            modelBuilder.Entity("Data.Models.Return_Policy", b =>
                {
                    b.Property<int>("Return_Policy_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Return_Policy_Id"));

                    b.Property<bool>("Can_Return")
                        .HasColumnType("bit");

                    b.Property<string>("Pasport_Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<string>("Signature1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Signature2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Return_Policy_Id");

                    b.ToTable("return_policies", (string)null);

                    b.HasData(
                        new
                        {
                            Return_Policy_Id = 1,
                            Can_Return = false,
                            Pasport_Data = "AA1234567",
                            Reason = "Wrong medicine purchased",
                            SaleId = 1,
                            Signature1 = "O. Ivanov",
                            Signature2 = "Pharmacist A"
                        },
                        new
                        {
                            Return_Policy_Id = 2,
                            Can_Return = false,
                            Pasport_Data = "BB7654321",
                            Reason = "Allergic reaction",
                            SaleId = 2,
                            Signature1 = "Y. Moroz",
                            Signature2 = "Pharmacist B"
                        },
                        new
                        {
                            Return_Policy_Id = 3,
                            Can_Return = false,
                            Pasport_Data = "CC1122334",
                            Reason = "Expired product",
                            SaleId = 3,
                            Signature1 = "V. Kravchenko",
                            Signature2 = "Pharmacist C"
                        },
                        new
                        {
                            Return_Policy_Id = 4,
                            Can_Return = false,
                            Pasport_Data = "DD5566778",
                            Reason = "Doctor changed prescription",
                            SaleId = 4,
                            Signature1 = "I. Savchenko",
                            Signature2 = "Pharmacist A"
                        },
                        new
                        {
                            Return_Policy_Id = 5,
                            Can_Return = false,
                            Pasport_Data = "EE9988776",
                            Reason = "Duplicate purchase",
                            SaleId = 5,
                            Signature1 = "D. Polishchuk",
                            Signature2 = "Pharmacist D"
                        });
                });

            modelBuilder.Entity("Data.Models.Sale", b =>
                {
                    b.Property<int>("Sale_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sale_Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("Customer_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date_Of_Sale")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Return_Policy_Id")
                        .HasColumnType("int");

                    b.HasKey("Sale_Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("Return_Policy_Id")
                        .IsUnique()
                        .HasFilter("[Return_Policy_Id] IS NOT NULL");

                    b.ToTable("sales", (string)null);

                    b.HasData(
                        new
                        {
                            Sale_Id = 1,
                            BatchId = 1,
                            Customer_Name = "Oleksandr Ivanov",
                            Date_Of_Sale = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 1,
                            Price = 25.50m,
                            Quantity = 2,
                            Return_Policy_Id = 1
                        },
                        new
                        {
                            Sale_Id = 2,
                            BatchId = 2,
                            Customer_Name = "Yulia Moroz",
                            Date_Of_Sale = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 2,
                            Price = 18.00m,
                            Quantity = 1,
                            Return_Policy_Id = 2
                        },
                        new
                        {
                            Sale_Id = 3,
                            BatchId = 4,
                            Customer_Name = "Viktor Kravchenko",
                            Date_Of_Sale = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 4,
                            Price = 45.00m,
                            Quantity = 3,
                            Return_Policy_Id = 3
                        },
                        new
                        {
                            Sale_Id = 4,
                            BatchId = 5,
                            Customer_Name = "Iryna Savchenko",
                            Date_Of_Sale = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 5,
                            Price = 32.00m,
                            Quantity = 2,
                            Return_Policy_Id = 4
                        },
                        new
                        {
                            Sale_Id = 5,
                            BatchId = 6,
                            Customer_Name = "Dmytro Polishchuk",
                            Date_Of_Sale = new DateTime(2024, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 6,
                            Price = 55.00m,
                            Quantity = 1,
                            Return_Policy_Id = 5
                        },
                        new
                        {
                            Sale_Id = 6,
                            BatchId = 10,
                            Customer_Name = "Tetiana Melnyk",
                            Date_Of_Sale = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 7,
                            Price = 68.00m,
                            Quantity = 4
                        },
                        new
                        {
                            Sale_Id = 7,
                            BatchId = 7,
                            Customer_Name = "Mykola Boyko",
                            Date_Of_Sale = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 8,
                            Price = 28.50m,
                            Quantity = 2
                        },
                        new
                        {
                            Sale_Id = 8,
                            BatchId = 8,
                            Customer_Name = "Oksana Koval",
                            Date_Of_Sale = new DateTime(2024, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 9,
                            Price = 12.00m,
                            Quantity = 1
                        },
                        new
                        {
                            Sale_Id = 9,
                            BatchId = 1,
                            Customer_Name = "Roman Sokolenko",
                            Date_Of_Sale = new DateTime(2024, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 1,
                            Price = 42.00m,
                            Quantity = 3
                        },
                        new
                        {
                            Sale_Id = 10,
                            BatchId = 2,
                            Customer_Name = "Lesia Hrytsenko",
                            Date_Of_Sale = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 2,
                            Price = 36.00m,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("Data.Models.Shelf", b =>
                {
                    b.Property<int>("ShelfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShelfId"));

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int>("ShelfNumber")
                        .HasColumnType("int");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ShelfId");

                    b.ToTable("shelves", (string)null);

                    b.HasData(
                        new
                        {
                            ShelfId = 1,
                            RowNumber = 1,
                            ShelfNumber = 1,
                            Zone = "Zone A"
                        },
                        new
                        {
                            ShelfId = 2,
                            RowNumber = 2,
                            ShelfNumber = 1,
                            Zone = "Zone A"
                        },
                        new
                        {
                            ShelfId = 3,
                            RowNumber = 1,
                            ShelfNumber = 2,
                            Zone = "Zone A"
                        },
                        new
                        {
                            ShelfId = 4,
                            RowNumber = 1,
                            ShelfNumber = 1,
                            Zone = "Zone B"
                        },
                        new
                        {
                            ShelfId = 5,
                            RowNumber = 2,
                            ShelfNumber = 1,
                            Zone = "Zone B"
                        },
                        new
                        {
                            ShelfId = 6,
                            RowNumber = 1,
                            ShelfNumber = 2,
                            Zone = "Zone B"
                        },
                        new
                        {
                            ShelfId = 7,
                            RowNumber = 1,
                            ShelfNumber = 1,
                            Zone = "Zone C"
                        },
                        new
                        {
                            ShelfId = 8,
                            RowNumber = 2,
                            ShelfNumber = 1,
                            Zone = "Zone C"
                        },
                        new
                        {
                            ShelfId = 9,
                            RowNumber = 1,
                            ShelfNumber = 2,
                            Zone = "Zone C"
                        },
                        new
                        {
                            ShelfId = 10,
                            RowNumber = 1,
                            ShelfNumber = 1,
                            Zone = "Zone D"
                        });
                });

            modelBuilder.Entity("Data.Models.Shelf_Item", b =>
                {
                    b.Property<int>("Shelf_Item_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Shelf_Item_Id"));

                    b.Property<int>("Face_Current")
                        .HasColumnType("int");

                    b.Property<int>("Face_Required")
                        .HasColumnType("int");

                    b.Property<DateTime>("Last_Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location_Hint")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("ShelfId")
                        .HasColumnType("int");

                    b.HasKey("Shelf_Item_Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("ShelfId");

                    b.ToTable("shelf_items", (string)null);

                    b.HasData(
                        new
                        {
                            Shelf_Item_Id = 1,
                            Face_Current = 8,
                            Face_Required = 10,
                            Last_Updated = new DateTime(2024, 11, 13, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Location_Hint = "Left side",
                            MedicineId = 1,
                            ShelfId = 1
                        },
                        new
                        {
                            Shelf_Item_Id = 2,
                            Face_Current = 12,
                            Face_Required = 15,
                            Last_Updated = new DateTime(2024, 11, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Location_Hint = "Center",
                            MedicineId = 2,
                            ShelfId = 1
                        },
                        new
                        {
                            Shelf_Item_Id = 3,
                            Face_Current = 6,
                            Face_Required = 8,
                            Last_Updated = new DateTime(2024, 11, 7, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Location_Hint = "Right side",
                            MedicineId = 3,
                            ShelfId = 2
                        },
                        new
                        {
                            Shelf_Item_Id = 4,
                            Face_Current = 18,
                            Face_Required = 20,
                            Last_Updated = new DateTime(2024, 11, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Location_Hint = "Top shelf",
                            MedicineId = 4,
                            ShelfId = 3
                        },
                        new
                        {
                            Shelf_Item_Id = 5,
                            Face_Current = 10,
                            Face_Required = 12,
                            Last_Updated = new DateTime(2024, 11, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Location_Hint = "Bottom",
                            MedicineId = 5,
                            ShelfId = 4
                        },
                        new
                        {
                            Shelf_Item_Id = 6,
                            Face_Current = 7,
                            Face_Required = 9,
                            Last_Updated = new DateTime(2024, 11, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Location_Hint = "Left corner",
                            MedicineId = 6,
                            ShelfId = 5
                        },
                        new
                        {
                            Shelf_Item_Id = 7,
                            Face_Current = 16,
                            Face_Required = 18,
                            Last_Updated = new DateTime(2024, 11, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Location_Hint = "Middle row",
                            MedicineId = 7,
                            ShelfId = 6
                        },
                        new
                        {
                            Shelf_Item_Id = 8,
                            Face_Current = 11,
                            Face_Required = 14,
                            Last_Updated = new DateTime(2024, 11, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Location_Hint = "Right corner",
                            MedicineId = 8,
                            ShelfId = 7
                        },
                        new
                        {
                            Shelf_Item_Id = 9,
                            Face_Current = 5,
                            Face_Required = 7,
                            Last_Updated = new DateTime(2024, 11, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Location_Hint = "Front facing",
                            MedicineId = 9,
                            ShelfId = 8
                        },
                        new
                        {
                            Shelf_Item_Id = 10,
                            Face_Current = 9,
                            Face_Required = 11,
                            Last_Updated = new DateTime(2024, 12, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Location_Hint = "Back row",
                            MedicineId = 10,
                            ShelfId = 9
                        });
                });

            modelBuilder.Entity("Data.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SupplierId");

                    b.ToTable("suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Phone = "+380501234567",
                            SupplierName = "MedSupply Co."
                        },
                        new
                        {
                            SupplierId = 2,
                            Phone = "+380502345678",
                            SupplierName = "PharmaDistribution Ltd."
                        },
                        new
                        {
                            SupplierId = 3,
                            Phone = "+380503456789",
                            SupplierName = "HealthCare Supplies"
                        },
                        new
                        {
                            SupplierId = 4,
                            Phone = "+380504567890",
                            SupplierName = "Global Pharma Inc."
                        },
                        new
                        {
                            SupplierId = 5,
                            Phone = "+380505678901",
                            SupplierName = "MediWorld Trading"
                        },
                        new
                        {
                            SupplierId = 6,
                            Phone = "+380506789012",
                            SupplierName = "PharmaTech Solutions"
                        },
                        new
                        {
                            SupplierId = 7,
                            Phone = "+380507890123",
                            SupplierName = "BioMed Distributors"
                        },
                        new
                        {
                            SupplierId = 8,
                            Phone = "+380508901234",
                            SupplierName = "EuroPharma Group"
                        },
                        new
                        {
                            SupplierId = 9,
                            Phone = "+380509012345",
                            SupplierName = "MedExpress Logistics"
                        },
                        new
                        {
                            SupplierId = 10,
                            Phone = "+380500123456",
                            SupplierName = "Pharmaceutical Wholesale"
                        });
                });

            modelBuilder.Entity("Data.Models.Batch", b =>
                {
                    b.HasOne("Data.Models.Medicine", "Medicine")
                        .WithMany("Batches")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Purchase_Order", "Purchase_Order")
                        .WithMany()
                        .HasForeignKey("Purchase_OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Purchase_Order_Item", "Purchase_Order_Item")
                        .WithMany()
                        .HasForeignKey("Purchase_Order_ItemId");

                    b.HasOne("Data.Models.Refrigerator", "Refrigerator")
                        .WithMany("Batches")
                        .HasForeignKey("RefrigeratorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Medicine");

                    b.Navigation("Purchase_Order");

                    b.Navigation("Purchase_Order_Item");

                    b.Navigation("Refrigerator");
                });

            modelBuilder.Entity("Data.Models.Medicine", b =>
                {
                    b.HasOne("Data.Models.Active_Ingredient", "Active_Ingredient")
                        .WithMany("Medicines")
                        .HasForeignKey("Active_IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Brand", "Brand")
                        .WithMany("Medicines")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Active_Ingredient");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Data.Models.Purchase_Order", b =>
                {
                    b.HasOne("Data.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Data.Models.Purchase_Order_Item", b =>
                {
                    b.HasOne("Data.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Purchase_Order", "Purchase_Order")
                        .WithMany("Items")
                        .HasForeignKey("Purchase_orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Purchase_Order");
                });

            modelBuilder.Entity("Data.Models.Recipe", b =>
                {
                    b.HasOne("Data.Models.Medicine", "Medicine")
                        .WithMany("Recipes")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("Data.Models.Refrigerator_Log", b =>
                {
                    b.HasOne("Data.Models.Refrigerator", "Refrigerator")
                        .WithMany("Logs")
                        .HasForeignKey("RefrigeratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Refrigerator");
                });

            modelBuilder.Entity("Data.Models.Sale", b =>
                {
                    b.HasOne("Data.Models.Batch", "Batch")
                        .WithMany("Sales")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Medicine", "Medicine")
                        .WithMany("Sales")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Return_Policy", "Return_Policy")
                        .WithOne("Sale")
                        .HasForeignKey("Data.Models.Sale", "Return_Policy_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Batch");

                    b.Navigation("Medicine");

                    b.Navigation("Return_Policy");
                });

            modelBuilder.Entity("Data.Models.Shelf_Item", b =>
                {
                    b.HasOne("Data.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Shelf", "Shelf")
                        .WithMany("ShelfItems")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("Data.Models.Active_Ingredient", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("Data.Models.Batch", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Data.Models.Brand", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("Data.Models.Medicine", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Recipes");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Data.Models.Purchase_Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Data.Models.Refrigerator", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Data.Models.Return_Policy", b =>
                {
                    b.Navigation("Sale")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Models.Shelf", b =>
                {
                    b.Navigation("ShelfItems");
                });
#pragma warning restore 612, 618
        }
    }
}
