// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(MonitoringContext))]
    [Migration("20260206171052_NameO")]
    partial class NameO
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("LogId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EntityType", "EntityId", "Timestamp");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            LogId = 1,
                            Action = "ServiceCheck",
                            Description = "Автоматична перевірка сервісу 'Корпоративний портал': Success (245 мс)",
                            EntityId = 1,
                            EntityType = "Service",
                            Timestamp = new DateTime(2026, 1, 31, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 2,
                            Action = "IncidentCreated",
                            Description = "Автоматично створено інцидент 'Повільна робота порталу' (тригер: High Response Time)",
                            EntityId = 1,
                            EntityType = "Incident",
                            Timestamp = new DateTime(2026, 1, 20, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 3,
                            Action = "IncidentResolved",
                            Description = "Вирішено інцидент 'Повільна робота порталу'. Причина: Високе навантаження. Рішення: Оптимізовано SQL запити.",
                            EmployeeId = 1,
                            EntityId = 1,
                            EntityType = "Incident",
                            Timestamp = new DateTime(2026, 1, 20, 11, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 4,
                            Action = "ServiceCreated",
                            Description = "Створено новий сервіс 'Backup Server' (категорія: File Systems, критичність: High)",
                            EmployeeId = 1,
                            EntityId = 9,
                            EntityType = "Service",
                            Timestamp = new DateTime(2026, 1, 25, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 5,
                            Action = "ServiceUpdated",
                            Description = "Оновлено сервіс 'Корпоративний портал': Змінено CheckInterval з 5 на 10 хвилин",
                            EmployeeId = 1,
                            EntityId = 1,
                            EntityType = "Service",
                            Timestamp = new DateTime(2026, 1, 26, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 6,
                            Action = "ServiceDeleted",
                            Description = "Видалено сервіс 'Old API Server' (був неактивний понад 6 місяців)",
                            EmployeeId = 1,
                            EntityId = 15,
                            EntityType = "Service",
                            Timestamp = new DateTime(2026, 1, 28, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 7,
                            Action = "MaintenanceScheduled",
                            Description = "Заплановано обслуговування 'Оновлення PostgreSQL до версії 15' на 15.01.2026 02:00-03:00",
                            EmployeeId = 2,
                            EntityId = 1,
                            EntityType = "MaintenanceWindow",
                            Timestamp = new DateTime(2026, 1, 10, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Data.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "IT Department",
                            Description = "Загальний IT відділ"
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "DevOps Team",
                            Description = "Команда DevOps інженерів"
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Infrastructure",
                            Description = "Інфраструктурний відділ"
                        },
                        new
                        {
                            DepartmentId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Security",
                            Description = "Відділ безпеки"
                        },
                        new
                        {
                            DepartmentId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Database Administration",
                            Description = "Адміністратори баз даних"
                        });
                });

            modelBuilder.Entity("Data.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DepartmentId = 1,
                            Email = "i.petrenko@company.local",
                            FullName = "Петренко Іван Михайлович",
                            Phone = "+380501234567",
                            Position = "System Administrator",
                            SpecializationId = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            DepartmentId = 5,
                            Email = "o.kovalenko@company.local",
                            FullName = "Коваленко Олена Петрівна",
                            Phone = "+380502345678",
                            Position = "Database Administrator",
                            SpecializationId = 2
                        },
                        new
                        {
                            EmployeeId = 3,
                            DepartmentId = 2,
                            Email = "a.shevchenko@company.local",
                            FullName = "Шевченко Андрій Сергійович",
                            Phone = "+380503456789",
                            Position = "Senior DevOps Engineer",
                            SpecializationId = 5
                        },
                        new
                        {
                            EmployeeId = 4,
                            DepartmentId = 3,
                            Email = "m.bondarenko@company.local",
                            FullName = "Бондаренко Марія Олександрівна",
                            Phone = "+380504567890",
                            Position = "Network Engineer",
                            SpecializationId = 3
                        },
                        new
                        {
                            EmployeeId = 5,
                            DepartmentId = 4,
                            Email = "s.lysenko@company.local",
                            FullName = "Лисенко Сергій Васильович",
                            Phone = "+380505678901",
                            Position = "Security Specialist",
                            SpecializationId = 4
                        });
                });

            modelBuilder.Entity("Data.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentId"));

                    b.Property<int?>("AssignedToEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DowntimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Recommendations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RootCause")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SeverityId")
                        .HasColumnType("int");

                    b.Property<string>("Solution")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TriggeredByTriggerId")
                        .HasColumnType("int");

                    b.HasKey("IncidentId");

                    b.HasIndex("AssignedToEmployeeId");

                    b.HasIndex("SeverityId");

                    b.HasIndex("TriggeredByTriggerId");

                    b.HasIndex("ServiceId", "Status");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            IncidentId = 1,
                            AssignedToEmployeeId = 1,
                            ClosedAt = new DateTime(2026, 1, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Користувачі скаржаться на повільне завантаження сторінок. Час відповіді перевищує 4 секунди.",
                            DetectedAt = new DateTime(2026, 1, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            DowntimeMinutes = 0,
                            Priority = "Medium",
                            Recommendations = "Розглянути масштабування сервера або впровадження load balancer. Провести аудит всіх SQL запитів.",
                            ResolvedAt = new DateTime(2026, 1, 20, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            RootCause = "Високе навантаження через велику кількість користувачів одночасно. SQL запити виконувались без індексів.",
                            ServiceId = 1,
                            SeverityId = 2,
                            Solution = "Оптимізовано SQL запити до бази даних, додано індекси на таблиці users та sessions, впроваджено кешування для статичних ресурсів",
                            Status = "Closed",
                            Title = "Повільна робота порталу",
                            TriggeredByTriggerId = 1
                        },
                        new
                        {
                            IncidentId = 2,
                            AssignedToEmployeeId = 2,
                            Description = "Періодичні втрати з'єднання з базою даних PostgreSQL. Транзакції не завершуються.",
                            DetectedAt = new DateTime(2026, 1, 25, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            DowntimeMinutes = 15,
                            Priority = "High",
                            Recommendations = "Впровадити моніторинг пулу з'єднань через pg_stat_activity. Оптимізувати довгі транзакції у додатках.",
                            ResolvedAt = new DateTime(2026, 1, 25, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            RootCause = "Переповнення пулу з'єднань через некоректну конфігурацію max_connections=100. Під час пікового навантаження всі з'єднання були зайняті.",
                            ServiceId = 2,
                            SeverityId = 3,
                            Solution = "Збільшено max_connections з 100 до 200, збільшено shared_buffers до 4GB, перезапущено PostgreSQL",
                            Status = "Resolved",
                            Title = "Перебої у роботі бази даних"
                        },
                        new
                        {
                            IncidentId = 3,
                            AssignedToEmployeeId = 4,
                            Description = "Неможливо надіслати або отримати електронну пошту. SMTP порт 25 не відповідає на з'єднання.",
                            DetectedAt = new DateTime(2024, 1, 30, 10, 20, 48, 0, DateTimeKind.Unspecified),
                            DowntimeMinutes = 25,
                            Priority = "Critical",
                            ServiceId = 5,
                            SeverityId = 4,
                            Status = "InProgress",
                            Title = "Поштовий сервер недоступний",
                            TriggeredByTriggerId = 3
                        },
                        new
                        {
                            IncidentId = 4,
                            Description = "API платежів відповідає повільно, час обробки транзакцій збільшився до 6 секунд замість звичних 200мс",
                            DetectedAt = new DateTime(2024, 1, 20, 10, 15, 48, 0, DateTimeKind.Unspecified),
                            Priority = "High",
                            ServiceId = 8,
                            SeverityId = 3,
                            Status = "New",
                            Title = "Підвищений час відповіді API платежів"
                        },
                        new
                        {
                            IncidentId = 5,
                            AssignedToEmployeeId = 4,
                            ClosedAt = new DateTime(2026, 1, 22, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "DNS сервер припинив обробку запитів. Всі сервіси втратили можливість резолвити доменні імена.",
                            DetectedAt = new DateTime(2026, 1, 22, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            DowntimeMinutes = 15,
                            Priority = "Critical",
                            Recommendations = "Оновити BIND9 до останньої версії. Додати моніторинг процесу BIND9 з автоматичним перезапуском.",
                            ResolvedAt = new DateTime(2026, 1, 22, 16, 25, 0, 0, DateTimeKind.Unspecified),
                            RootCause = "Процес BIND9 завершився через помилку сегментації (segmentation fault). Виявлено в /var/log/syslog.",
                            ServiceId = 7,
                            SeverityId = 3,
                            Solution = "Перезапущено BIND9 через systemctl restart bind9. Виконано перевірку конфігурації named-checkconf.",
                            Status = "Closed",
                            Title = "DNS сервер не відповідав"
                        });
                });

            modelBuilder.Entity("Data.Models.IncidentComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit");

                    b.HasKey("CommentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentComments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            CommentText = "Виявлено проблему зі SQL запитами. Розпочинаю оптимізацію.",
                            CreatedAt = new DateTime(2026, 1, 20, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            IncidentId = 1,
                            IsInternal = true
                        },
                        new
                        {
                            CommentId = 2,
                            CommentText = "Оптимізацію завершено. Тестую продуктивність на тестовому середовищі.",
                            CreatedAt = new DateTime(2026, 1, 20, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            IncidentId = 1,
                            IsInternal = true
                        },
                        new
                        {
                            CommentId = 3,
                            CommentText = "Зміни застосовано на продакшні. Час відповіді знизився до 300мс. Проблема вирішена.",
                            CreatedAt = new DateTime(2026, 1, 20, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            IncidentId = 1,
                            IsInternal = false
                        },
                        new
                        {
                            CommentId = 4,
                            CommentText = "Перевіряю логи PostgreSQL. Виявлено помилки: 'FATAL: sorry, too many clients already'",
                            CreatedAt = new DateTime(2026, 1, 25, 14, 35, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            IncidentId = 2,
                            IsInternal = true
                        },
                        new
                        {
                            CommentId = 5,
                            CommentText = "Збільшено max_connections та shared_buffers. Перезапуск PostgreSQL запланований на 15:30.",
                            CreatedAt = new DateTime(2026, 1, 25, 15, 20, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            IncidentId = 2,
                            IsInternal = true
                        },
                        new
                        {
                            CommentId = 6,
                            CommentText = "PostgreSQL перезапущено успішно. З'єднання стабільні. Моніторю ситуацію.",
                            CreatedAt = new DateTime(2026, 1, 25, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            IncidentId = 2,
                            IsInternal = false
                        },
                        new
                        {
                            CommentId = 7,
                            CommentText = "Підключаюсь до поштового серверу для діагностики. Перевіряю статус служби Postfix.",
                            CreatedAt = new DateTime(2024, 1, 20, 10, 0, 48, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            IncidentId = 3,
                            IsInternal = true
                        },
                        new
                        {
                            CommentId = 8,
                            AttachmentPath = "/uploads/incidents/3/postfix_status_screenshot.png",
                            CommentText = "Служба Postfix зупинена. Додаю скріншот помилки з systemctl status.",
                            CreatedAt = new DateTime(2024, 1, 20, 10, 5, 48, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            IncidentId = 3,
                            IsInternal = true
                        },
                        new
                        {
                            CommentId = 9,
                            AttachmentPath = "/uploads/incidents/3/mailq_output.txt",
                            CommentText = "Перевіряю логи mail queue. Виявлено переповнення черги (50000+ листів).",
                            CreatedAt = new DateTime(2024, 1, 20, 10, 10, 48, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            IncidentId = 3,
                            IsInternal = true
                        });
                });

            modelBuilder.Entity("Data.Models.IncidentSeverity", b =>
                {
                    b.Property<int>("SeverityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeverityId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ExpectedResolutionTimeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("NotifyManagement")
                        .HasColumnType("bit");

                    b.Property<string>("SeverityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SeverityId");

                    b.ToTable("IncidentSeverities");

                    b.HasData(
                        new
                        {
                            SeverityId = 1,
                            Description = "Незначний вплив на роботу",
                            ExpectedResolutionTimeMinutes = 240,
                            NotifyManagement = false,
                            SeverityName = "Minor"
                        },
                        new
                        {
                            SeverityId = 2,
                            Description = "Помірний вплив на функціонал",
                            ExpectedResolutionTimeMinutes = 120,
                            NotifyManagement = false,
                            SeverityName = "Moderate"
                        },
                        new
                        {
                            SeverityId = 3,
                            Description = "Значний вплив на бізнес-процеси",
                            ExpectedResolutionTimeMinutes = 60,
                            NotifyManagement = true,
                            SeverityName = "Major"
                        },
                        new
                        {
                            SeverityId = 4,
                            Description = "Критичний збій, повна зупинка сервісу",
                            ExpectedResolutionTimeMinutes = 30,
                            NotifyManagement = true,
                            SeverityName = "Critical"
                        });
                });

            modelBuilder.Entity("Data.Models.MaintenanceWindow", b =>
                {
                    b.Property<int>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceId"));

                    b.Property<DateTime?>("ActualEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImpactDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("NotifyUsers")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ScheduledByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaintenanceId");

                    b.HasIndex("ScheduledByEmployeeId");

                    b.HasIndex("ServiceId", "StartDateTime", "EndDateTime");

                    b.ToTable("MaintenanceWindows");

                    b.HasData(
                        new
                        {
                            MaintenanceId = 1,
                            ActualEndDateTime = new DateTime(2026, 1, 15, 2, 45, 0, 0, DateTimeKind.Unspecified),
                            ActualStartDateTime = new DateTime(2026, 1, 15, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Планове оновлення СУБД для покращення продуктивності та безпеки",
                            EndDateTime = new DateTime(2026, 1, 15, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            ImpactDescription = "База даних буде повністю недоступна протягом 1 години. Всі додатки, що використовують БД, не працюватимуть.",
                            NotifyUsers = true,
                            Reason = "Software Update",
                            ScheduledByEmployeeId = 2,
                            ServiceId = 2,
                            StartDateTime = new DateTime(2026, 1, 15, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            Title = "Оновлення PostgreSQL до версії 15"
                        },
                        new
                        {
                            MaintenanceId = 2,
                            Description = "Критичні патчі безпеки для Apache веб-сервера (CVE-2024-XXXX)",
                            EndDateTime = new DateTime(2024, 1, 22, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            ImpactDescription = "Корпоративний портал буде недоступний близько 1 години",
                            NotifyUsers = true,
                            Reason = "Security Patch",
                            ScheduledByEmployeeId = 1,
                            ServiceId = 1,
                            StartDateTime = new DateTime(2024, 1, 22, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Scheduled",
                            Title = "Встановлення security патчів"
                        },
                        new
                        {
                            MaintenanceId = 3,
                            Description = "Превентивна заміна диску D: через виявлені помилки SMART",
                            EndDateTime = new DateTime(2024, 1, 25, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            ImpactDescription = "Файловий сервер буде недоступний 2 години. Робота з файлами неможлива.",
                            NotifyUsers = true,
                            Reason = "Hardware Replacement",
                            ScheduledByEmployeeId = 3,
                            ServiceId = 4,
                            StartDateTime = new DateTime(2024, 1, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Scheduled",
                            Title = "Заміна жорсткого диску"
                        });
                });

            modelBuilder.Entity("Data.Models.MonitoringCheck", b =>
                {
                    b.Property<int>("CheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckId"));

                    b.Property<DateTime>("CheckDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ResponseTime")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("CheckId");

                    b.HasIndex("ServiceId");

                    b.ToTable("MonitoringChecks");

                    b.HasData(
                        new
                        {
                            CheckId = 1,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 20, 48, 0, DateTimeKind.Unspecified),
                            ResponseTime = 245,
                            ServiceId = 1,
                            Status = "Success",
                            StatusCode = 200
                        },
                        new
                        {
                            CheckId = 2,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 25, 48, 0, DateTimeKind.Unspecified),
                            ResponseTime = 280,
                            ServiceId = 1,
                            Status = "Success",
                            StatusCode = 200
                        },
                        new
                        {
                            CheckId = 3,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 30, 48, 0, DateTimeKind.Unspecified),
                            ResponseTime = 310,
                            ServiceId = 1,
                            Status = "Success",
                            StatusCode = 200
                        },
                        new
                        {
                            CheckId = 4,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 35, 48, 0, DateTimeKind.Unspecified),
                            Details = "Response time exceeds warning threshold",
                            ResponseTime = 4500,
                            ServiceId = 1,
                            Status = "Warning",
                            StatusCode = 200
                        },
                        new
                        {
                            CheckId = 5,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 40, 48, 0, DateTimeKind.Unspecified),
                            ErrorMessage = "Connection timeout after 10 seconds",
                            ServiceId = 1,
                            Status = "Error"
                        },
                        new
                        {
                            CheckId = 6,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 45, 48, 0, DateTimeKind.Unspecified),
                            Details = "Service recovered",
                            ResponseTime = 280,
                            ServiceId = 1,
                            Status = "Success",
                            StatusCode = 200
                        },
                        new
                        {
                            CheckId = 7,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 20, 48, 0, DateTimeKind.Unspecified),
                            ResponseTime = 50,
                            ServiceId = 2,
                            Status = "Success"
                        },
                        new
                        {
                            CheckId = 8,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 25, 48, 0, DateTimeKind.Unspecified),
                            ResponseTime = 45,
                            ServiceId = 2,
                            Status = "Success"
                        },
                        new
                        {
                            CheckId = 9,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 20, 48, 0, DateTimeKind.Unspecified),
                            ResponseTime = 120,
                            ServiceId = 8,
                            Status = "Success",
                            StatusCode = 200
                        },
                        new
                        {
                            CheckId = 10,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 25, 48, 0, DateTimeKind.Unspecified),
                            ResponseTime = 135,
                            ServiceId = 8,
                            Status = "Success",
                            StatusCode = 200
                        },
                        new
                        {
                            CheckId = 11,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 20, 48, 0, DateTimeKind.Unspecified),
                            ResponseTime = 100,
                            ServiceId = 4,
                            Status = "Success"
                        },
                        new
                        {
                            CheckId = 12,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 35, 48, 0, DateTimeKind.Unspecified),
                            ResponseTime = 95,
                            ServiceId = 4,
                            Status = "Success"
                        },
                        new
                        {
                            CheckId = 13,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 20, 48, 0, DateTimeKind.Unspecified),
                            ResponseTime = 80,
                            ServiceId = 5,
                            Status = "Success"
                        },
                        new
                        {
                            CheckId = 14,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 25, 48, 0, DateTimeKind.Unspecified),
                            ResponseTime = 75,
                            ServiceId = 5,
                            Status = "Success"
                        },
                        new
                        {
                            CheckId = 15,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 20, 48, 0, DateTimeKind.Unspecified),
                            ResponseTime = 15,
                            ServiceId = 7,
                            Status = "Success"
                        },
                        new
                        {
                            CheckId = 16,
                            CheckDateTime = new DateTime(2024, 1, 20, 9, 25, 48, 0, DateTimeKind.Unspecified),
                            ResponseTime = 12,
                            ServiceId = 7,
                            Status = "Success"
                        });
                });

            modelBuilder.Entity("Data.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CheckInterval")
                        .HasColumnType("int");

                    b.Property<string>("CheckMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriticalResponseTime")
                        .HasColumnType("int");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExpectedResponseContains")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ExpectedStatusCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxConsecutiveFailures")
                        .HasColumnType("int");

                    b.Property<decimal>("MinUptimePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("NetworkAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsibleEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Timeout")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("WarningResponseTime")
                        .HasColumnType("int");

                    b.HasKey("ServiceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ResponsibleEmployeeId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            CategoryId = 1,
                            CheckInterval = 5,
                            CheckMethod = "HTTP_GET",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CriticalResponseTime = 10000,
                            Criticality = "High",
                            Description = "Внутрішній веб-портал для співробітників",
                            ExpectedStatusCode = 200,
                            IsActive = true,
                            MaxConsecutiveFailures = 3,
                            MinUptimePercent = 99.5m,
                            NetworkAddress = "192.168.1.100",
                            Port = 443,
                            ResponsibleEmployeeId = 1,
                            RetryCount = 3,
                            ServiceName = "Корпоративний портал",
                            ServiceType = "HTTP",
                            Timeout = 10,
                            Url = "https://intranet.company.local",
                            WarningResponseTime = 3000
                        },
                        new
                        {
                            ServiceId = 2,
                            CategoryId = 2,
                            CheckInterval = 5,
                            CheckMethod = "TCP_Connect",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CriticalResponseTime = 5000,
                            Criticality = "Critical",
                            Description = "PostgreSQL база даних для бухгалтерської системи",
                            ExpectedStatusCode = 200,
                            IsActive = true,
                            MaxConsecutiveFailures = 2,
                            MinUptimePercent = 99.9m,
                            NetworkAddress = "192.168.1.101",
                            Port = 5432,
                            ResponsibleEmployeeId = 2,
                            RetryCount = 3,
                            ServiceName = "База даних бухгалтерії",
                            ServiceType = "Database",
                            Timeout = 10,
                            WarningResponseTime = 2000
                        },
                        new
                        {
                            ServiceId = 3,
                            CategoryId = 1,
                            CheckInterval = 5,
                            CheckMethod = "HTTP_GET",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CriticalResponseTime = 10000,
                            Criticality = "High",
                            Description = "Система управління взаємовідносинами з клієнтами",
                            ExpectedStatusCode = 200,
                            IsActive = true,
                            MaxConsecutiveFailures = 3,
                            MinUptimePercent = 99.5m,
                            NetworkAddress = "192.168.1.102",
                            Port = 443,
                            ResponsibleEmployeeId = 3,
                            RetryCount = 3,
                            ServiceName = "CRM система",
                            ServiceType = "HTTP",
                            Timeout = 10,
                            Url = "https://crm.company.local",
                            WarningResponseTime = 3000
                        },
                        new
                        {
                            ServiceId = 4,
                            CategoryId = 3,
                            CheckInterval = 15,
                            CheckMethod = "TCP_Connect",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CriticalResponseTime = 5000,
                            Criticality = "High",
                            Description = "Корпоративне сховище файлів",
                            ExpectedStatusCode = 200,
                            IsActive = true,
                            MaxConsecutiveFailures = 3,
                            MinUptimePercent = 99.0m,
                            NetworkAddress = "192.168.1.103",
                            Port = 445,
                            ResponsibleEmployeeId = 4,
                            RetryCount = 3,
                            ServiceName = "Файловий сервер",
                            ServiceType = "FileSystem",
                            Timeout = 10,
                            WarningResponseTime = 2000
                        },
                        new
                        {
                            ServiceId = 5,
                            CategoryId = 4,
                            CheckInterval = 5,
                            CheckMethod = "TCP_Connect",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CriticalResponseTime = 5000,
                            Criticality = "Critical",
                            Description = "Корпоративна поштова система",
                            ExpectedStatusCode = 200,
                            IsActive = true,
                            MaxConsecutiveFailures = 2,
                            MinUptimePercent = 99.9m,
                            NetworkAddress = "mail.company.local",
                            Port = 25,
                            ResponsibleEmployeeId = 4,
                            RetryCount = 3,
                            ServiceName = "Поштовий сервер",
                            ServiceType = "TCP",
                            Timeout = 10,
                            WarningResponseTime = 2000
                        },
                        new
                        {
                            ServiceId = 6,
                            CategoryId = 4,
                            CheckInterval = 10,
                            CheckMethod = "TCP_Connect",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CriticalResponseTime = 5000,
                            Criticality = "High",
                            Description = "VPN для віддаленого доступу",
                            ExpectedStatusCode = 200,
                            IsActive = true,
                            MaxConsecutiveFailures = 3,
                            MinUptimePercent = 99.0m,
                            NetworkAddress = "vpn.company.local",
                            Port = 1194,
                            ResponsibleEmployeeId = 5,
                            RetryCount = 3,
                            ServiceName = "VPN сервер",
                            ServiceType = "TCP",
                            Timeout = 10,
                            WarningResponseTime = 2000
                        },
                        new
                        {
                            ServiceId = 7,
                            CategoryId = 4,
                            CheckInterval = 5,
                            CheckMethod = "TCP_Connect",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CriticalResponseTime = 3000,
                            Criticality = "Critical",
                            Description = "Внутрішній DNS",
                            ExpectedStatusCode = 200,
                            IsActive = true,
                            MaxConsecutiveFailures = 2,
                            MinUptimePercent = 99.9m,
                            NetworkAddress = "dns.company.local",
                            Port = 53,
                            ResponsibleEmployeeId = 4,
                            RetryCount = 3,
                            ServiceName = "DNS сервер",
                            ServiceType = "TCP",
                            Timeout = 5,
                            WarningResponseTime = 1000
                        },
                        new
                        {
                            ServiceId = 8,
                            CategoryId = 5,
                            CheckInterval = 5,
                            CheckMethod = "HTTP_GET",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CriticalResponseTime = 5000,
                            Criticality = "Critical",
                            Description = "REST API для обробки онлайн-платежів",
                            ExpectedResponseContains = "{\"status\":\"ok\"}",
                            ExpectedStatusCode = 200,
                            IsActive = true,
                            MaxConsecutiveFailures = 2,
                            MinUptimePercent = 99.9m,
                            NetworkAddress = "192.168.1.104",
                            Port = 443,
                            ResponsibleEmployeeId = 3,
                            RetryCount = 3,
                            ServiceName = "API платежів",
                            ServiceType = "HTTP",
                            Timeout = 10,
                            Url = "https://payment-api.company.local/health",
                            WarningResponseTime = 2000
                        });
                });

            modelBuilder.Entity("Data.Models.ServiceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryId");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Web Services",
                            Description = "Веб-додатки та портали"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Databases",
                            Description = "Системи управління базами даних"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "File Systems",
                            Description = "Файлові сервери та сховища"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Network Services",
                            Description = "DNS, VPN, DHCP тощо"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "APIs",
                            Description = "REST/SOAP API сервіси"
                        });
                });

            modelBuilder.Entity("Data.Models.ServiceDependency", b =>
                {
                    b.Property<int>("DependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DependencyId"));

                    b.Property<string>("DependencyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DependsOnServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("DependencyId");

                    b.HasIndex("DependsOnServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceDependencies");

                    b.HasData(
                        new
                        {
                            DependencyId = 1,
                            DependencyType = "Required",
                            DependsOnServiceId = 2,
                            Description = "CRM не може працювати без бази даних",
                            ServiceId = 3
                        },
                        new
                        {
                            DependencyId = 2,
                            DependencyType = "Optional",
                            DependsOnServiceId = 4,
                            Description = "Портал працює, але не можна завантажити файли",
                            ServiceId = 1
                        },
                        new
                        {
                            DependencyId = 3,
                            DependencyType = "Required",
                            DependsOnServiceId = 7,
                            Description = "API потребує DNS для роботи",
                            ServiceId = 8
                        },
                        new
                        {
                            DependencyId = 4,
                            DependencyType = "Optional",
                            DependsOnServiceId = 8,
                            Description = "Портал працює, але онлайн-оплата недоступна",
                            ServiceId = 1
                        });
                });

            modelBuilder.Entity("Data.Models.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecializationId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SpecializationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpecializationId");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            SpecializationId = 1,
                            Description = "Спеціалізація на веб-сервісах та HTTP",
                            SpecializationName = "Web Services"
                        },
                        new
                        {
                            SpecializationId = 2,
                            Description = "Експерти по базам даних",
                            SpecializationName = "Databases"
                        },
                        new
                        {
                            SpecializationId = 3,
                            Description = "Мережеві спеціалісти",
                            SpecializationName = "Network Infrastructure"
                        },
                        new
                        {
                            SpecializationId = 4,
                            Description = "Спеціалісти з безпеки",
                            SpecializationName = "Security"
                        },
                        new
                        {
                            SpecializationId = 5,
                            Description = "Універсальні DevOps інженери",
                            SpecializationName = "DevOps"
                        });
                });

            modelBuilder.Entity("Data.Models.SpecializationCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("SpecializationCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            SpecializationId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            SpecializationId = 3
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            SpecializationId = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            SpecializationId = 4
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            SpecializationId = 4
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            SpecializationId = 4
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            SpecializationId = 5
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            SpecializationId = 5
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            SpecializationId = 5
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            SpecializationId = 5
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            SpecializationId = 5
                        });
                });

            modelBuilder.Entity("Data.Models.Trigger", b =>
                {
                    b.Property<int>("TriggerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TriggerId"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ConsecutiveChecks")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncidentPriority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IncidentSeverityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("ThresholdValue")
                        .HasColumnType("int");

                    b.Property<string>("TriggerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TriggerId");

                    b.HasIndex("IncidentSeverityId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Triggers");

                    b.HasData(
                        new
                        {
                            TriggerId = 1,
                            Condition = ">",
                            ConsecutiveChecks = 3,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentPriority = "Medium",
                            IncidentSeverityId = 2,
                            IsEnabled = true,
                            ServiceId = 1,
                            ThresholdValue = 3000,
                            TriggerName = "High Response Time",
                            TriggerType = "ResponseTime"
                        },
                        new
                        {
                            TriggerId = 2,
                            Condition = "== Offline",
                            ConsecutiveChecks = 2,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentPriority = "Critical",
                            IncidentSeverityId = 4,
                            IsEnabled = true,
                            ServiceId = 2,
                            TriggerName = "Database Unavailable",
                            TriggerType = "Availability"
                        },
                        new
                        {
                            TriggerId = 3,
                            Condition = ">=",
                            ConsecutiveChecks = 1,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentPriority = "High",
                            IncidentSeverityId = 3,
                            IsEnabled = true,
                            ServiceId = 5,
                            ThresholdValue = 3,
                            TriggerName = "Multiple Connection Failures",
                            TriggerType = "ConsecutiveFailures"
                        },
                        new
                        {
                            TriggerId = 4,
                            Condition = ">",
                            ConsecutiveChecks = 2,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentPriority = "Critical",
                            IncidentSeverityId = 4,
                            IsEnabled = true,
                            ServiceId = 8,
                            ThresholdValue = 5000,
                            TriggerName = "Critical API Response Time",
                            TriggerType = "ResponseTime"
                        });
                });

            modelBuilder.Entity("Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Data.Models.AuditLog", b =>
                {
                    b.HasOne("Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Data.Models.Employee", b =>
                {
                    b.HasOne("Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Data.Models.Specialization", "Specialization")
                        .WithMany("Employees")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Data.Models.Incident", b =>
                {
                    b.HasOne("Data.Models.Employee", "AssignedToEmployee")
                        .WithMany("AssignedIncidents")
                        .HasForeignKey("AssignedToEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Data.Models.Service", "Service")
                        .WithMany("Incidents")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.IncidentSeverity", "Severity")
                        .WithMany("Incidents")
                        .HasForeignKey("SeverityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Trigger", "TriggeredByTrigger")
                        .WithMany("TriggeredIncidents")
                        .HasForeignKey("TriggeredByTriggerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedToEmployee");

                    b.Navigation("Service");

                    b.Navigation("Severity");

                    b.Navigation("TriggeredByTrigger");
                });

            modelBuilder.Entity("Data.Models.IncidentComment", b =>
                {
                    b.HasOne("Data.Models.Employee", "Employee")
                        .WithMany("Comments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Incident", "Incident")
                        .WithMany("Comments")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Data.Models.MaintenanceWindow", b =>
                {
                    b.HasOne("Data.Models.Employee", "ScheduledByEmployee")
                        .WithMany("ScheduledMaintenances")
                        .HasForeignKey("ScheduledByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Service", "Service")
                        .WithMany("MaintenanceWindows")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScheduledByEmployee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Data.Models.MonitoringCheck", b =>
                {
                    b.HasOne("Data.Models.Service", "Service")
                        .WithMany("MonitoringChecks")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Data.Models.Service", b =>
                {
                    b.HasOne("Data.Models.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Employee", "ResponsibleEmployee")
                        .WithMany("ResponsibleServices")
                        .HasForeignKey("ResponsibleEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("ResponsibleEmployee");
                });

            modelBuilder.Entity("Data.Models.ServiceDependency", b =>
                {
                    b.HasOne("Data.Models.Service", "DependsOnService")
                        .WithMany("DependentServices")
                        .HasForeignKey("DependsOnServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Service", "Service")
                        .WithMany("Dependencies")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DependsOnService");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Data.Models.SpecializationCategory", b =>
                {
                    b.HasOne("Data.Models.ServiceCategory", "Category")
                        .WithMany("SpecializationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Specialization", "Specialization")
                        .WithMany("SpecializationCategories")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Data.Models.Trigger", b =>
                {
                    b.HasOne("Data.Models.IncidentSeverity", "IncidentSeverity")
                        .WithMany("Triggers")
                        .HasForeignKey("IncidentSeverityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Service", "Service")
                        .WithMany("Triggers")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncidentSeverity");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Data.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Data.Models.Employee", b =>
                {
                    b.Navigation("AssignedIncidents");

                    b.Navigation("Comments");

                    b.Navigation("ResponsibleServices");

                    b.Navigation("ScheduledMaintenances");
                });

            modelBuilder.Entity("Data.Models.Incident", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Data.Models.IncidentSeverity", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("Triggers");
                });

            modelBuilder.Entity("Data.Models.Service", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("DependentServices");

                    b.Navigation("Incidents");

                    b.Navigation("MaintenanceWindows");

                    b.Navigation("MonitoringChecks");

                    b.Navigation("Triggers");
                });

            modelBuilder.Entity("Data.Models.ServiceCategory", b =>
                {
                    b.Navigation("Services");

                    b.Navigation("SpecializationCategories");
                });

            modelBuilder.Entity("Data.Models.Specialization", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("SpecializationCategories");
                });

            modelBuilder.Entity("Data.Models.Trigger", b =>
                {
                    b.Navigation("TriggeredIncidents");
                });
#pragma warning restore 612, 618
        }
    }
}
