// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(FinalProjectContext))]
    partial class FinalProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.BillingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BillingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("BillingRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 1,
                            Description = "Feb Storage",
                            PeriodEnd = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 1500.00m
                        },
                        new
                        {
                            Id = 2,
                            BillingDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 2,
                            Description = "Feb Cold Chain",
                            PeriodEnd = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 3000.00m
                        },
                        new
                        {
                            Id = 3,
                            BillingDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 3,
                            Description = "Feb Bulk",
                            PeriodEnd = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 500.00m
                        },
                        new
                        {
                            Id = 4,
                            BillingDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 4,
                            Description = "Feb Retail",
                            PeriodEnd = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 200.00m
                        },
                        new
                        {
                            Id = 5,
                            BillingDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 5,
                            Description = "Feb Secure",
                            PeriodEnd = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 2500.00m
                        },
                        new
                        {
                            Id = 6,
                            BillingDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 6,
                            Description = "Feb Parts",
                            PeriodEnd = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 450.00m
                        },
                        new
                        {
                            Id = 7,
                            BillingDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 7,
                            Description = "Feb Hazardous",
                            PeriodEnd = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 5000.00m
                        },
                        new
                        {
                            Id = 8,
                            BillingDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 8,
                            Description = "Feb E-comm",
                            PeriodEnd = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 800.00m
                        },
                        new
                        {
                            Id = 9,
                            BillingDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 9,
                            Description = "Feb Frozen",
                            PeriodEnd = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 1200.00m
                        },
                        new
                        {
                            Id = 10,
                            BillingDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 10,
                            Description = "Feb VIP",
                            PeriodEnd = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 10000.00m
                        });
                });

            modelBuilder.Entity("Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TariffPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TariffPlanId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "TechNova",
                            Email = "contact@technova.com",
                            Phone = "+380501112233",
                            TariffPlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "GreenGrocer",
                            Email = "supply@greengrocer.ua",
                            Phone = "+380672223344",
                            TariffPlanId = 3
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "BuildMaster",
                            Email = "info@buildmaster.com",
                            Phone = "+380633334455",
                            TariffPlanId = 5
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Fashionista",
                            Email = "logistics@fashionista.com",
                            Phone = "+380994445566",
                            TariffPlanId = 1
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "MediCare Pharm",
                            Email = "warehouse@medicare.com",
                            Phone = "+380975556677",
                            TariffPlanId = 2
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "AutoParts UA",
                            Email = "sales@autoparts.ua",
                            Phone = "+380506667788",
                            TariffPlanId = 1
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "ChemSolutions",
                            Email = "safety@chemsolutions.com",
                            Phone = "+380637778899",
                            TariffPlanId = 6
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "ToyWonderland",
                            Email = "kids@toywonderland.com",
                            Phone = "+380958889900",
                            TariffPlanId = 4
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "FrozenDelights",
                            Email = "ice@frozendelights.com",
                            Phone = "+380679990011",
                            TariffPlanId = 3
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "LuxuryImports",
                            Email = "vip@luxuryimports.com",
                            Phone = "+380501234567",
                            TariffPlanId = 10
                        });
                });

            modelBuilder.Entity("Data.Models.InboundOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("InboundOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            Date = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            Date = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            Date = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 4,
                            Date = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 5,
                            Date = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "New"
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 6,
                            Date = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 7,
                            Date = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Processing"
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 8,
                            Date = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "New"
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 9,
                            Date = new DateTime(2024, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 10,
                            Date = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "New"
                        });
                });

            modelBuilder.Entity("Data.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StorageBinId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StorageBinId");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Quantity = 50,
                            StorageBinId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArrivalDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Quantity = 1000,
                            StorageBinId = 4
                        },
                        new
                        {
                            Id = 3,
                            ArrivalDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3,
                            Quantity = 200,
                            StorageBinId = 5
                        },
                        new
                        {
                            Id = 4,
                            ArrivalDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4,
                            Quantity = 150,
                            StorageBinId = 10
                        },
                        new
                        {
                            Id = 5,
                            ArrivalDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 5,
                            Quantity = 500,
                            StorageBinId = 3
                        },
                        new
                        {
                            Id = 6,
                            ArrivalDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 6,
                            Quantity = 80,
                            StorageBinId = 2
                        },
                        new
                        {
                            Id = 7,
                            ArrivalDate = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 7,
                            Quantity = 20,
                            StorageBinId = 6
                        },
                        new
                        {
                            Id = 8,
                            ArrivalDate = new DateTime(2024, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 8,
                            Quantity = 60,
                            StorageBinId = 2
                        },
                        new
                        {
                            Id = 9,
                            ArrivalDate = new DateTime(2024, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 9,
                            Quantity = 300,
                            StorageBinId = 9
                        },
                        new
                        {
                            Id = 10,
                            ArrivalDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 10,
                            Quantity = 10,
                            StorageBinId = 3
                        });
                });

            modelBuilder.Entity("Data.Models.OutboundOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("OutboundOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            Date = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            Date = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            Date = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 4,
                            Date = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 5,
                            Date = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 6,
                            Date = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 7,
                            Date = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 8,
                            Date = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Packing"
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 9,
                            Date = new DateTime(2024, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 10,
                            Date = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            Description = "High-end laptop",
                            Height = 0.05m,
                            Length = 0.4m,
                            Name = "Laptop Pro 15",
                            SKU = "TECH-001",
                            Weight = 2.0m,
                            Width = 0.3m
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            Description = "Fresh fruits",
                            Height = 0.3m,
                            Length = 0.5m,
                            Name = "Organic Apples",
                            SKU = "FOOD-055",
                            Weight = 10.0m,
                            Width = 0.4m
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            Description = "50kg bags",
                            Height = 0.2m,
                            Length = 0.8m,
                            Name = "Cement Bags",
                            SKU = "BLD-999",
                            Weight = 50.0m,
                            Width = 0.5m
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 4,
                            Description = "Men's parka",
                            Height = 0.1m,
                            Length = 0.6m,
                            Name = "Winter Jacket",
                            SKU = "CLTH-WIN-01",
                            Weight = 1.2m,
                            Width = 0.4m
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 5,
                            Description = "Controlled substance",
                            Height = 0.1m,
                            Length = 0.2m,
                            Name = "Antibiotics X",
                            SKU = "MED-AB-100",
                            Weight = 0.5m,
                            Width = 0.1m
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 6,
                            Description = "Ceramic pads",
                            Height = 0.1m,
                            Length = 0.3m,
                            Name = "Brake Pads",
                            SKU = "AUTO-BRK-22",
                            Weight = 3.0m,
                            Width = 0.2m
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 7,
                            Description = "Corrosive",
                            Height = 0.6m,
                            Length = 0.4m,
                            Name = "Industrial Acid",
                            SKU = "CHEM-ACD-05",
                            Weight = 25.0m,
                            Width = 0.4m
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 8,
                            Description = "Construction set",
                            Height = 0.15m,
                            Length = 0.5m,
                            Name = "Lego Set Large",
                            SKU = "TOY-LEG-500",
                            Weight = 1.5m,
                            Width = 0.3m
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 9,
                            Description = "Keep frozen",
                            Height = 0.1m,
                            Length = 0.2m,
                            Name = "Vanilla Ice Cream",
                            SKU = "FOOD-ICE-01",
                            Weight = 0.5m,
                            Width = 0.15m
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 10,
                            Description = "Luxury item",
                            Height = 0.05m,
                            Length = 0.1m,
                            Name = "Gold Watch",
                            SKU = "LUX-WTC-007",
                            Weight = 0.3m,
                            Width = 0.1m
                        });
                });

            modelBuilder.Entity("Data.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FromBinId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ToBinId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FromBinId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ToBinId");

                    b.ToTable("StockMovements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovementDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Quantity = 50,
                            ToBinId = 1,
                            Type = "Inbound"
                        },
                        new
                        {
                            Id = 2,
                            MovementDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Quantity = 1000,
                            ToBinId = 4,
                            Type = "Inbound"
                        },
                        new
                        {
                            Id = 3,
                            MovementDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3,
                            Quantity = 200,
                            ToBinId = 5,
                            Type = "Inbound"
                        },
                        new
                        {
                            Id = 4,
                            FromBinId = 1,
                            MovementDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Quantity = 5,
                            Type = "Outbound"
                        },
                        new
                        {
                            Id = 5,
                            FromBinId = 4,
                            MovementDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Quantity = 10,
                            ToBinId = 8,
                            Type = "Relocation"
                        },
                        new
                        {
                            Id = 6,
                            MovementDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 5,
                            Quantity = 500,
                            ToBinId = 3,
                            Type = "Inbound"
                        },
                        new
                        {
                            Id = 7,
                            FromBinId = 10,
                            MovementDate = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4,
                            Quantity = 2,
                            Type = "Outbound"
                        },
                        new
                        {
                            Id = 8,
                            MovementDate = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 7,
                            Quantity = 20,
                            ToBinId = 6,
                            Type = "Inbound"
                        },
                        new
                        {
                            Id = 9,
                            FromBinId = 2,
                            MovementDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 6,
                            Quantity = 5,
                            ToBinId = 1,
                            Type = "Relocation"
                        },
                        new
                        {
                            Id = 10,
                            FromBinId = 3,
                            MovementDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 10,
                            Quantity = 1,
                            Type = "Outbound"
                        });
                });

            modelBuilder.Entity("Data.Models.StorageBin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxVolume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StorageZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StorageZoneId");

                    b.ToTable("StorageBins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "A-01-01",
                            MaxVolume = 2.0m,
                            MaxWeight = 500m,
                            StorageZoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "A-01-02",
                            MaxVolume = 2.0m,
                            MaxWeight = 500m,
                            StorageZoneId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "B-05-10",
                            MaxVolume = 1.0m,
                            MaxWeight = 200m,
                            StorageZoneId = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "C-COLD-01",
                            MaxVolume = 1.5m,
                            MaxWeight = 300m,
                            StorageZoneId = 3
                        },
                        new
                        {
                            Id = 5,
                            Code = "D-BULK-99",
                            MaxVolume = 10.0m,
                            MaxWeight = 5000m,
                            StorageZoneId = 4
                        },
                        new
                        {
                            Id = 6,
                            Code = "E-HAZ-01",
                            MaxVolume = 0.5m,
                            MaxWeight = 100m,
                            StorageZoneId = 5
                        },
                        new
                        {
                            Id = 7,
                            Code = "F-ELEC-05",
                            MaxVolume = 1.0m,
                            MaxWeight = 150m,
                            StorageZoneId = 6
                        },
                        new
                        {
                            Id = 8,
                            Code = "G-FOOD-22",
                            MaxVolume = 2.0m,
                            MaxWeight = 400m,
                            StorageZoneId = 7
                        },
                        new
                        {
                            Id = 9,
                            Code = "H-FRZ-01",
                            MaxVolume = 1.5m,
                            MaxWeight = 300m,
                            StorageZoneId = 8
                        },
                        new
                        {
                            Id = 10,
                            Code = "I-TEX-07",
                            MaxVolume = 3.0m,
                            MaxWeight = 200m,
                            StorageZoneId = 9
                        });
                });

            modelBuilder.Entity("Data.Models.StorageZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StorageZones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostMultiplier = 1.0m,
                            Name = "Zone A (General)",
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            CostMultiplier = 1.5m,
                            Name = "Zone B (Secure)",
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 3,
                            CostMultiplier = 2.0m,
                            Name = "Zone C (Cold)",
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 4,
                            CostMultiplier = 0.8m,
                            Name = "Zone D (Bulk)",
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 5,
                            CostMultiplier = 3.0m,
                            Name = "Zone E (Hazardous)",
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 6,
                            CostMultiplier = 1.2m,
                            Name = "Zone F (Electronics)",
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 7,
                            CostMultiplier = 1.1m,
                            Name = "Zone G (Food)",
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 8,
                            CostMultiplier = 2.5m,
                            Name = "Zone H (Freezer)",
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 9,
                            CostMultiplier = 1.0m,
                            Name = "Zone I (Textile)",
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 10,
                            CostMultiplier = 0.5m,
                            Name = "Zone J (Returns)",
                            WarehouseId = 1
                        });
                });

            modelBuilder.Entity("Data.Models.TariffPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DailyStorageCostPerCubicMeter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HandlingFeePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TariffPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyStorageCostPerCubicMeter = 10.0m,
                            HandlingFeePerUnit = 5.0m,
                            Name = "Standard Retail"
                        },
                        new
                        {
                            Id = 2,
                            DailyStorageCostPerCubicMeter = 20.0m,
                            HandlingFeePerUnit = 10.0m,
                            Name = "Premium Secure"
                        },
                        new
                        {
                            Id = 3,
                            DailyStorageCostPerCubicMeter = 30.0m,
                            HandlingFeePerUnit = 15.0m,
                            Name = "Cold Chain"
                        },
                        new
                        {
                            Id = 4,
                            DailyStorageCostPerCubicMeter = 12.0m,
                            HandlingFeePerUnit = 3.0m,
                            Name = "E-commerce Lite"
                        },
                        new
                        {
                            Id = 5,
                            DailyStorageCostPerCubicMeter = 8.0m,
                            HandlingFeePerUnit = 2.0m,
                            Name = "Wholesale Bulk"
                        },
                        new
                        {
                            Id = 6,
                            DailyStorageCostPerCubicMeter = 50.0m,
                            HandlingFeePerUnit = 25.0m,
                            Name = "Hazardous Material"
                        },
                        new
                        {
                            Id = 7,
                            DailyStorageCostPerCubicMeter = 5.0m,
                            HandlingFeePerUnit = 10.0m,
                            Name = "Long Term Storage"
                        },
                        new
                        {
                            Id = 8,
                            DailyStorageCostPerCubicMeter = 15.0m,
                            HandlingFeePerUnit = 20.0m,
                            Name = "Express Handling"
                        },
                        new
                        {
                            Id = 9,
                            DailyStorageCostPerCubicMeter = 18.0m,
                            HandlingFeePerUnit = 12.0m,
                            Name = "Fragile Goods"
                        },
                        new
                        {
                            Id = 10,
                            DailyStorageCostPerCubicMeter = 25.0m,
                            HandlingFeePerUnit = 0.0m,
                            Name = "VIP Client"
                        });
                });

            modelBuilder.Entity("Data.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kyiv, Industrialna 1",
                            Name = "Kyiv Central Hub"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Lviv, Horodotska 220",
                            Name = "Lviv West Terminal"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Odesa, Prymorska 5",
                            Name = "Odesa Port Logistics"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Kharkiv, Gagarina 10",
                            Name = "Kharkiv East Depot"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Dnipro, Slobozhansky 15",
                            Name = "Dnipro Cargo Center"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Kyiv, Kilceva 4",
                            Name = "Kyiv Cold Storage"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Poltava, Kyivske Hwy 3",
                            Name = "Poltava Distribution"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Vinnytsia, Khmelnytske Hwy 7",
                            Name = "Vinnytsia Transit"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Zaporizhzhia, Metalurgiv 2",
                            Name = "Zaporizhzhia Industrial"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Uzhhorod, Sobranetska 100",
                            Name = "Uzhhorod Border Hub"
                        });
                });

            modelBuilder.Entity("Data.Models.BillingRecord", b =>
                {
                    b.HasOne("Data.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Data.Models.Client", b =>
                {
                    b.HasOne("Data.Models.TariffPlan", "TariffPlan")
                        .WithMany("Clients")
                        .HasForeignKey("TariffPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TariffPlan");
                });

            modelBuilder.Entity("Data.Models.InboundOrder", b =>
                {
                    b.HasOne("Data.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Data.Models.InventoryItem", b =>
                {
                    b.HasOne("Data.Models.Product", "Product")
                        .WithMany("InventoryItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.StorageBin", "StorageBin")
                        .WithMany("Items")
                        .HasForeignKey("StorageBinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StorageBin");
                });

            modelBuilder.Entity("Data.Models.OutboundOrder", b =>
                {
                    b.HasOne("Data.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Data.Models.Product", b =>
                {
                    b.HasOne("Data.Models.Client", "Client")
                        .WithMany("Products")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Data.Models.StockMovement", b =>
                {
                    b.HasOne("Data.Models.StorageBin", "FromBin")
                        .WithMany()
                        .HasForeignKey("FromBinId");

                    b.HasOne("Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.StorageBin", "ToBin")
                        .WithMany()
                        .HasForeignKey("ToBinId");

                    b.Navigation("FromBin");

                    b.Navigation("Product");

                    b.Navigation("ToBin");
                });

            modelBuilder.Entity("Data.Models.StorageBin", b =>
                {
                    b.HasOne("Data.Models.StorageZone", "StorageZone")
                        .WithMany("Bins")
                        .HasForeignKey("StorageZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageZone");
                });

            modelBuilder.Entity("Data.Models.StorageZone", b =>
                {
                    b.HasOne("Data.Models.Warehouse", "Warehouse")
                        .WithMany("Zones")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Data.Models.Client", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Data.Models.Product", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("Data.Models.StorageBin", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Data.Models.StorageZone", b =>
                {
                    b.Navigation("Bins");
                });

            modelBuilder.Entity("Data.Models.TariffPlan", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Data.Models.Warehouse", b =>
                {
                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
